# Generated by Django 3.2 on 2023-07-01 19:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(max_length=100, verbose_name='Job role')),
                ('end_date', models.PositiveSmallIntegerField(verbose_name='End date')),
                ('start_date', models.PositiveSmallIntegerField(verbose_name='Start date')),
                ('role_description', models.TextField(max_length=125, verbose_name='Role description')),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PYTHON', 'Python'), ('NEXTJS', 'Next JS'), ('REACTJS', 'React JS'), ('POSTGRESQL', 'PostgreSQL'), ('AMAZONWEBSERVICES', 'Amazon Web Services'), ('DJANGO', 'Django Web Framework'), ('DJANGORESTFRAMEWORK', 'Django Rest Framework')], max_length=30, verbose_name='Role skills')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
