# Generated by Django 3.2 on 2023-07-01 19:14

import applications.project.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField(verbose_name='Website')),
                ('dev_year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('title', models.CharField(max_length=30, verbose_name='Project title')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('in_production', models.BooleanField(default=False, verbose_name='Is in production')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=applications.project.models.screenshot_file_name, verbose_name='Screenshot')),
                ('technologies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PYTHON', 'Python'), ('NEXTJS', 'Next JS'), ('REACTJS', 'React JS'), ('POSTGRESQL', 'PostgreSQL'), ('AMAZONWEBSERVICES', 'Amazon Web Services'), ('DJANGO', 'Django Web Framework'), ('DJANGORESTFRAMEWORK', 'Django Rest Framework')], max_length=20, verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
