# Generated by Django 3.2 on 2023-07-01 19:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('current_job', models.CharField(max_length=75, verbose_name='Current job')),
                ('creator_name', models.CharField(max_length=50, verbose_name='Creator name')),
                ('self_description', models.TextField(max_length=125, verbose_name='Self escription')),
                ('short_self_description', models.TextField(max_length=60, verbose_name='Short self description')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
